export const citiesList = [
  { name: "Paris" },
  { name: "Bangkok" },
  { name: "London" },
  { name: "Dubai" },
  { name: "New York City" },
  { name: "Singapore" },
  { name: "Istanbul" },
  { name: "Tokyo" },
  { name: "Rome" },
  { name: "Barcelona" },
  { name: "Amsterdam" },
  { name: "Prague" },
  { name: "Venice" },
  { name: "Sydney" },
  { name: "Cairo" },
  { name: "Cape Town" },
  { name: "Rio de Janeiro" },
  { name: "Hong Kong" },
  { name: "Los Angeles" },
  { name: "San Francisco" },
  { name: "Las Vegas" },
  { name: "Beijing" },
  { name: "Seoul" },
  { name: "Berlin" },
  { name: "Vienna" },
  { name: "Budapest" },
  { name: "Marrakech" },
  { name: "Hanoi" },
  { name: "Kuala Lumpur" },
  { name: "Delhi" },
  { name: "Mumbai" },
  { name: "Agra" },
  { name: "Florence" },
  { name: "Edinburgh" },
  { name: "Cusco" },
  { name: "Machu Picchu" },
  { name: "Zurich" },
  { name: "Stockholm" },
  { name: "Reykjavik" },
  { name: "Toronto" },
  { name: "Vancouver" },
  { name: "Montreal" },
  { name: "Mexico City" },
  { name: "Santiago" },
  { name: "Copenhagen" },
  { name: "Dublin" },
  { name: "Jerusalem" },
  { name: "Cairo" },
  { name: "Havana" },
  { name: "Beirut" },
  { name: "Manila" },
  { name: "Bali" },
  { name: "Auckland" },
  { name: "Wellington" },
  { name: "Buenos Aires" },
  { name: "Sao Paulo" },
  { name: "Rio de Janeiro" },
  { name: "Cape Town" },
  { name: "Marrakech" },
  { name: "Dubai" },
  { name: "Phuket" },
  { name: "Bali" },
  { name: "Honolulu" },
  { name: "San Diego" },
  { name: "Milan" },
  { name: "Vienna" },
  { name: "Rome" },
  { name: "Moscow" },
  { name: "Beijing" },
  { name: "Shanghai" },
  { name: "Istanbul" },
  { name: "Antalya" },
  { name: "Cairo" },
  { name: "Lima" },
  { name: "Santiago" },
  { name: "Bogota" },
  { name: "Mexico City" },
  { name: "Toronto" },
  { name: "Vancouver" },
  { name: "Montreal" },
  { name: "New York City" },
  { name: "Los Angeles" },
  { name: "San Francisco" },
  { name: "Chicago" },
  { name: "Miami" },
  { name: "Orlando" },
  { name: "Atlanta" },
  { name: "New Orleans" },
];
