export const citiesList = [
  { name: "Placencia", destId: 23725 },
  { name: "Arad", destId: 25907 },
  { name: "Mont-St-Michel", destId: 25906 },
  { name: "Inle Lake", destId: 30026 },
  { name: "Leipzig", destId: 29263 },
  { name: "Gwalior", destId: 24829 },
  { name: "South Iceland", destId: 24828 },
  { name: "Madhya Pradesh", destId: 23970 },
  { name: "Grand Baie", destId: 23971 },
  { name: "Chitwan National Park", destId: 52061 },
  { name: "Wilpattu National Park", destId: 52062 },
  { name: "Anse La Raye", destId: 52064 },
  { name: "Matobo National Park - The Matopos", destId: 52068 },
  { name: "Lodz", destId: 32671 },
  { name: "Nazca", destId: 32679 },
  { name: "St George", destId: 23945 },
  { name: "Murchison Falls National Park", destId: 52073 },
  { name: "Ruaha National Park", destId: 52071 },
  { name: "Gorkhi Terelj National Park", destId: 52077 },
  { name: "Zacatecas", destId: 32422 },
  { name: "Udzungwa Mountains National Park", destId: 52079 },
  { name: "Sucre", destId: 23958 },
  { name: "Out Islands", destId: 23959 },
  { name: "Kibale National Park", destId: 52081 },
  { name: "Arraial do Cabo", destId: 31321 },
  { name: "Akagera National Park", destId: 52088 },
  { name: "Sandakan", destId: 32652 },
  { name: "Cafayate", destId: 31320 },
  { name: "Ba Be National Park", destId: 52089 },
  { name: "Fort Worth", destId: 33749 },
  { name: "My Son", destId: 33747 },
  { name: "Pereira", destId: 28161 },
  { name: "Otavalo", destId: 33748 },
  { name: "Lublin", destId: 50901 },
  { name: "Khasab", destId: 33746 },
  { name: "Vero Beach", destId: 50900 },
  { name: "Tampere", destId: 50903 },
  { name: "Madikeri", destId: 50904 },
  { name: "Turku", destId: 50907 },
  { name: "Golden Sands", destId: 50906 },
  { name: "Villach", destId: 50909 },
  { name: "Lujan de Cuyo", destId: 52093 },
  { name: "Central Sri Lanka", destId: 28132 },
  { name: "Albuquerque", destId: 28131 },
  { name: "Gamboa", destId: 31319 },
  { name: "Ometepe", destId: 31318 },
  { name: "Cabarete", destId: 31317 },
  { name: "Fort-de-France", destId: 50911 },
  { name: "Revelstoke", destId: 50914 },
  { name: "Rajkot", destId: 50913 },
  { name: "Evian-les-Bains", destId: 50916 },
  { name: "Collingwood", destId: 50915 },
  { name: "Foshan", destId: 50918 },
  { name: "Hsinchu County", destId: 50917 },
  { name: "Jabalpur", destId: 50921 },
  { name: "Maribor", destId: 50920 },
  { name: "Mossel Bay", destId: 50923 },
  { name: "Fontainebleau", destId: 50925 },
  { name: "Isla Chiloe", destId: 50924 },
  { name: "Puerto Galera", destId: 50927 },
  { name: "Maipu", destId: 50926 },
  { name: "Trois-Ilets", destId: 50929 },
  { name: "Ha Giang Province", destId: 50928 },
  { name: "Gili Islands", destId: 32622 },
  { name: "Kalbarri", destId: 50930 },
  { name: "Lower Saxony", destId: 30446 },
  { name: "Gansbaai", destId: 50931 },
  { name: "Roussillon", destId: 50935 },
  { name: "Lamego", destId: 50938 },
  { name: "Auxerre", destId: 50937 },
  { name: "Harare", destId: 31762 },
  { name: "Wurzburg", destId: 31761 },
  { name: "Nis", destId: 50941 },
  { name: "Pakse", destId: 28360 },
  { name: "Sao Martinho do Porto", destId: 50945 },
  { name: "Luzon", destId: 26182 },
  { name: "Bali", destId: 50944 },
  { name: "Todos Santos", destId: 24418 },
  { name: "Bandung", destId: 24417 },
  { name: "Kemer", destId: 23562 },
  { name: "Karlsruhe", destId: 25741 },
  { name: "Baden-Württemberg", destId: 25740 },
  { name: "Moselle Valley", destId: 25743 },
  { name: "Poznan", destId: 25742 },
  { name: "Poitou-Charentes", destId: 24414 },
  { name: "Algiers", destId: 25745 },
  { name: "Trier", destId: 25744 },
  { name: "La Rochelle", destId: 24415 },
  { name: "Mysore", destId: 25746 },
  { name: "San Vicente de la Sonsierra", destId: 51123 },
  { name: "Speyside", destId: 51126 },
  { name: "Vinh Long", destId: 51125 },
  { name: "Midigama", destId: 51128 },
  { name: "Urgench", destId: 51129 },
  { name: "Ayia Napa", destId: 31182 },
  { name: "Perak", destId: 25510 },
  { name: "Chandigarh", destId: 24420 },
  { name: "Protaras", destId: 31181 },
  { name: "Lilongwe", destId: 25512 },
  // { name: "Paris" },
  // { name: "Bangkok" },
  // { name: "London" },
  // { name: "Dubai" },
  // { name: "New York City" },
  // { name: "Singapore" },
  // { name: "Istanbul" },
  // { name: "Tokyo" },
  // { name: "Rome" },
  // { name: "Barcelona" },
  // { name: "Amsterdam" },
  // { name: "Prague" },
  // { name: "Venice" },
  // { name: "Sydney" },
  // { name: "Cairo" },
  // { name: "Cape Town" },
  // { name: "Rio de Janeiro" },
  // { name: "Hong Kong" },
  // { name: "Los Angeles" },
  // { name: "San Francisco" },
  // { name: "Las Vegas" },
  // { name: "Beijing" },
  // { name: "Seoul" },
  // { name: "Berlin" },
  // { name: "Vienna" },
  // { name: "Budapest" },
  // { name: "Marrakech" },
  // { name: "Hanoi" },
  // { name: "Kuala Lumpur" },
  // { name: "Delhi" },
  // { name: "Mumbai" },
  // { name: "Agra" },
  // { name: "Florence" },
  // { name: "Edinburgh" },
  // { name: "Cusco" },
  // { name: "Machu Picchu" },
  // { name: "Zurich" },
  // { name: "Stockholm" },
  // { name: "Reykjavik" },
  // { name: "Toronto" },
  // { name: "Vancouver" },
  // { name: "Montreal" },
  // { name: "Mexico City" },
  // { name: "Santiago" },
  // { name: "Copenhagen" },
  // { name: "Dublin" },
  // { name: "Jerusalem" },
  // { name: "Cairo" },
  // { name: "Havana" },
  // { name: "Beirut" },
  // { name: "Manila" },
  // { name: "Bali" },
  // { name: "Auckland" },
  // { name: "Wellington" },
  // { name: "Buenos Aires" },
  // { name: "Sao Paulo" },
  // { name: "Rio de Janeiro" },
  // { name: "Cape Town" },
  // { name: "Marrakech" },
  // { name: "Phuket" },
  // { name: "Bali" },
  // { name: "Honolulu" },
  // { name: "San Diego" },
  // { name: "Milan" },
  // { name: "Vienna" },
  // { name: "Rome" },
  // { name: "Moscow" },
  // { name: "Beijing" },
  // { name: "Shanghai" },
  // { name: "Istanbul" },
  // { name: "Antalya" },
  // { name: "Cairo" },
  // { name: "Lima" },
  // { name: "Santiago" },
  // { name: "Bogota" },
  // { name: "Mexico City" },
  // { name: "Toronto" },
  // { name: "Vancouver" },
  // { name: "Montreal" },
  // { name: "New York City" },
  // { name: "Los Angeles" },
  // { name: "San Francisco" },
  // { name: "Chicago" },
  // { name: "Miami" },
  // { name: "Orlando" },
  // { name: "Atlanta" },
  // { name: "New Orleans" },
  // { name: "Afghanistan", alpha2Code: "AF" },
  // { name: "Albania", alpha2Code: "AL" },
  // { name: "Algeria", alpha2Code: "DZ" },
  // { name: "Andorra", alpha2Code: "AD" },
  // { name: "Angola", alpha2Code: "AO" },
  // { name: "Antigua and Barbuda", alpha2Code: "AG" },
  // { name: "Argentina", alpha2Code: "AR" },
  // { name: "Armenia", alpha2Code: "AM" },
  // { name: "Australia", alpha2Code: "AU" },
  // { name: "Austria", alpha2Code: "AT" },
  // { name: "Azerbaijan", alpha2Code: "AZ" },
  // { name: "Bahamas", alpha2Code: "BS" },
  // { name: "Bahrain", alpha2Code: "BH" },
  // { name: "Bangladesh", alpha2Code: "BD" },
  // { name: "Barbados", alpha2Code: "BB" },
  // { name: "Belarus", alpha2Code: "BY" },
  // { name: "Belgium", alpha2Code: "BE" },
  // { name: "Belize", alpha2Code: "BZ" },
  // { name: "Benin", alpha2Code: "BJ" },
  // { name: "Bhutan", alpha2Code: "BT" },
  // { name: "Bolivia", alpha2Code: "BO" },
  // { name: "Bosnia and Herzegovina", alpha2Code: "BA" },
  // { name: "Botswana", alpha2Code: "BW" },
  // { name: "Brazil", alpha2Code: "BR" },
  // { name: "Brunei", alpha2Code: "BN" },
  // { name: "Bulgaria", alpha2Code: "BG" },
  // { name: "Burkina Faso", alpha2Code: "BF" },
  // { name: "Burundi", alpha2Code: "BI" },
  // { name: "Cabo Verde", alpha2Code: "CV" },
  // { name: "Cambodia", alpha2Code: "KH" },
  // { name: "Cameroon", alpha2Code: "CM" },
  // { name: "Canada", alpha2Code: "CA" },
  // { name: "Central African Republic", alpha2Code: "CF" },
  // { name: "Chad", alpha2Code: "TD" },
  // { name: "Chile", alpha2Code: "CL" },
  // { name: "China", alpha2Code: "CN" },
  // { name: "Colombia", alpha2Code: "CO" },
  // { name: "Comoros", alpha2Code: "KM" },
  // { name: "Congo", alpha2Code: "CG" },
  // { name: "Costa Rica", alpha2Code: "CR" },
  // { name: "Croatia", alpha2Code: "HR" },
  // { name: "Cuba", alpha2Code: "CU" },
  // { name: "Cyprus", alpha2Code: "CY" },
  // { name: "Czech Republic", alpha2Code: "CZ" },
  // { name: "Democratic Republic of the Congo", alpha2Code: "CD" },
  // { name: "Denmark", alpha2Code: "DK" },
  // { name: "Djibouti", alpha2Code: "DJ" },
  // { name: "Dominica", alpha2Code: "DM" },
  // { name: "Dominican Republic", alpha2Code: "DO" },
  // { name: "Ecuador", alpha2Code: "EC" },
  // { name: "Egypt", alpha2Code: "EG" },
  // { name: "El Salvador", alpha2Code: "SV" },
  // { name: "Equatorial Guinea", alpha2Code: "GQ" },
  // { name: "Eritrea", alpha2Code: "ER" },
  // { name: "Estonia", alpha2Code: "EE" },
  // { name: "Eswatini", alpha2Code: "SZ" },
  // { name: "Ethiopia", alpha2Code: "ET" },
  // { name: "Fiji", alpha2Code: "FJ" },
  // { name: "Finland", alpha2Code: "FI" },
  // { name: "France", alpha2Code: "FR" },
  // { name: "Gabon", alpha2Code: "GA" },
  // { name: "Gambia", alpha2Code: "GM" },
  // { name: "Georgia", alpha2Code: "GE" },
  // { name: "Germany", alpha2Code: "DE" },
  // { name: "Ghana", alpha2Code: "GH" },
  // { name: "Greece", alpha2Code: "GR" },
  // { name: "Grenada", alpha2Code: "GD" },
  // { name: "Guatemala", alpha2Code: "GT" },
  // { name: "Guinea", alpha2Code: "GN" },
  // { name: "Guinea-Bissau", alpha2Code: "GW" },
  // { name: "Guyana", alpha2Code: "GY" },
  // { name: "Haiti", alpha2Code: "HT" },
  // { name: "Honduras", alpha2Code: "HN" },
  // { name: "Hungary", alpha2Code: "HU" },
  // { name: "Iceland", alpha2Code: "IS" },
  // { name: "India", alpha2Code: "IN" },
  // { name: "Indonesia", alpha2Code: "ID" },
  // { name: "Iran", alpha2Code: "IR" },
  // { name: "Iraq", alpha2Code: "IQ" },
  // { name: "Ireland", alpha2Code: "IE" },
  // { name: "Israel", alpha2Code: "IL" },
  // { name: "Italy", alpha2Code: "IT" },
  // { name: "Jamaica", alpha2Code: "JM" },
  // { name: "Japan", alpha2Code: "JP" },
  // { name: "Jordan", alpha2Code: "JO" },
  // { name: "Kazakhstan", alpha2Code: "KZ" },
  // { name: "Kenya", alpha2Code: "KE" },
  // { name: "Kiribati", alpha2Code: "KI" },
  // { name: "Korea (North)", alpha2Code: "KP" },
  // { name: "Korea (South)", alpha2Code: "KR" },
  // { name: "Kosovo", alpha2Code: "XK" },
  // { name: "Kuwait", alpha2Code: "KW" },
  // { name: "Kyrgyzstan", alpha2Code: "KG" },
  // { name: "Laos", alpha2Code: "LA" },
  // { name: "Latvia", alpha2Code: "LV" },
  // { name: "Lebanon", alpha2Code: "LB" },
  // { name: "Lesotho", alpha2Code: "LS" },
  // { name: "Liberia", alpha2Code: "LR" },
  // { name: "Libya", alpha2Code: "LY" },
  // { name: "Liechtenstein", alpha2Code: "LI" },
  // { name: "Lithuania", alpha2Code: "LT" },
  // { name: "Luxembourg", alpha2Code: "LU" },
  // { name: "Madagascar", alpha2Code: "MG" },
  // { name: "Malawi", alpha2Code: "MW" },
  // { name: "Malaysia", alpha2Code: "MY" },
  // { name: "Maldives", alpha2Code: "MV" },
  // { name: "Mali", alpha2Code: "ML" },
  // { name: "Malta", alpha2Code: "MT" },
  // { name: "Marshall Islands", alpha2Code: "MH" },
  // { name: "Mauritania", alpha2Code: "MR" },
  // { name: "Mauritius", alpha2Code: "MU" },
  // { name: "Mexico", alpha2Code: "MX" },
  // { name: "Micronesia", alpha2Code: "FM" },
  // { name: "Moldova", alpha2Code: "MD" },
  // { name: "Monaco", alpha2Code: "MC" },
  // { name: "Mongolia", alpha2Code: "MN" },
  // { name: "Montenegro", alpha2Code: "ME" },
  // { name: "Morocco", alpha2Code: "MA" },
  // { name: "Mozambique", alpha2Code: "MZ" },
  // { name: "Myanmar", alpha2Code: "MM" },
  // { name: "Namibia", alpha2Code: "NA" },
  // { name: "Nauru", alpha2Code: "NR" },
  // { name: "Nepal", alpha2Code: "NP" },
  // { name: "Netherlands", alpha2Code: "NL" },
  // { name: "New Zealand", alpha2Code: "NZ" },
  // { name: "Nicaragua", alpha2Code: "NI" },
  // { name: "Niger", alpha2Code: "NE" },
  // { name: "Nigeria", alpha2Code: "NG" },
  // { name: "North Macedonia", alpha2Code: "MK" },
  // { name: "Norway", alpha2Code: "NO" },
  // { name: "Oman", alpha2Code: "OM" },
  // { name: "Pakistan", alpha2Code: "PK" },
  // { name: "Palau", alpha2Code: "PW" },
  // { name: "Panama", alpha2Code: "PA" },
  // { name: "Papua New Guinea", alpha2Code: "PG" },
  // { name: "Paraguay", alpha2Code: "PY" },
  // { name: "Peru", alpha2Code: "PE" },
  // { name: "Philippines", alpha2Code: "PH" },
  // { name: "Poland", alpha2Code: "PL" },
  // { name: "Portugal", alpha2Code: "PT" },
  // { name: "Qatar", alpha2Code: "QA" },
  // { name: "Romania", alpha2Code: "RO" },
  // { name: "Russia", alpha2Code: "RU" },
  // { name: "Rwanda", alpha2Code: "RW" },
  // { name: "Saint Kitts and Nevis", alpha2Code: "KN" },
  // { name: "Saint Lucia", alpha2Code: "LC" },
  // { name: "Saint Vincent and the Grenadines", alpha2Code: "VC" },
  // { name: "Samoa", alpha2Code: "WS" },
  // { name: "San Marino", alpha2Code: "SM" },
  // { name: "Sao Tome and Principe", alpha2Code: "ST" },
  // { name: "Saudi Arabia", alpha2Code: "SA" },
  // { name: "Senegal", alpha2Code: "SN" },
  // { name: "Serbia", alpha2Code: "RS" },
  // { name: "Seychelles", alpha2Code: "SC" },
  // { name: "Sierra Leone", alpha2Code: "SL" },
  // { name: "Singapore", alpha2Code: "SG" },
  // { name: "Slovakia", alpha2Code: "SK" },
  // { name: "Slovenia", alpha2Code: "SI" },
  // { name: "Solomon Islands", alpha2Code: "SB" },
  // { name: "Somalia", alpha2Code: "SO" },
  // { name: "South Africa", alpha2Code: "ZA" },
  // { name: "South Sudan", alpha2Code: "SS" },
  // { name: "Spain", alpha2Code: "ES" },
  // { name: "Sri Lanka", alpha2Code: "LK" },
  // { name: "Sudan", alpha2Code: "SD" },
  // { name: "Suriname", alpha2Code: "SR" },
  // { name: "Sweden", alpha2Code: "SE" },
  // { name: "Switzerland", alpha2Code: "CH" },
  // { name: "Syria", alpha2Code: "SY" },
  // { name: "Taiwan", alpha2Code: "TW" },
  // { name: "Tajikistan", alpha2Code: "TJ" },
  // { name: "Tanzania", alpha2Code: "TZ" },
  // { name: "Thailand", alpha2Code: "TH" },
  // { name: "Timor-Leste", alpha2Code: "TL" },
  // { name: "Togo", alpha2Code: "TG" },
  // { name: "Tonga", alpha2Code: "TO" },
  // { name: "Trinidad and Tobago", alpha2Code: "TT" },
  // { name: "Tunisia", alpha2Code: "TN" },
  // { name: "Turkey", alpha2Code: "TR" },
  // { name: "Turkmenistan", alpha2Code: "TM" },
  // { name: "Tuvalu", alpha2Code: "TV" },
  // { name: "Uganda", alpha2Code: "UG" },
  // { name: "Ukraine", alpha2Code: "UA" },
  // { name: "United Arab Emirates", alpha2Code: "AE" },
  // { name: "United Kingdom", alpha2Code: "GB" },
  // { name: "United States of America", alpha2Code: "US" },
  // { name: "Uruguay", alpha2Code: "UY" },
  // { name: "Uzbekistan", alpha2Code: "UZ" },
  // { name: "Vanuatu", alpha2Code: "VU" },
  // { name: "Vatican City", alpha2Code: "VA" },
  // { name: "Venezuela", alpha2Code: "VE" },
  // { name: "Vietnam", alpha2Code: "VN" },
  // { name: "Yemen", alpha2Code: "YE" },
  // { name: "Zambia", alpha2Code: "ZM" },
  // { name: "Zimbabwe", alpha2Code: "ZW" },
];
